### ISSUE TITLE
Debugger entered--Lisp error: (wrong-type-argument sequencep all)   cl-intersection((all magit) all)

### ISSUE THREAD

**Issue by avatar-lavventura** [dandavison/magit-delta#10] opened 2020-08-26 18:56 UTC
I am getting following error:

```
Debugger entered--Lisp error: (wrong-type-argument sequencep all)
  cl-intersection((all magit) all)

byte-code("\301\302!\210\301\303!\210\301\304!\210\301\305!\210\301\306\307\310#\203/\0\311\312\313\300!\205!\0\010\"\203/\0\314\315!\203/\0\315\316!\210\317\320\307\321\322\323\324\325&\007\\
210\317\326\307\327\324\320%\210\330\331\332\333\334DD\335\336\337\324\320\340\341&\011\210\330\342\332\333\343DD\344\324\320\340\345&\007\210\330\346\332\333\347DD\350\324\320\340\351&\007\2\
10\330\352\332\333\353DD\354\336\355\324\320\340\351&\011\210\330\356\332\333\357DD\360\324\320\340\361&\007\210\362\363\364\365\324\326%\210\362\366\367\370\324\326%\210\362\371\372\373\324\\
326%\210\362\374\375\376\324\326%\210\362\377\201@\0\201A\0\324\326%\207" [async-bytecomp-allowed-packages require button cl-lib dash format-spec async-bytecomp nil t cl-intersection (all
magit) boundp fboundp async-bytecomp-package-mode 1 custom-declare-group magit-popup "Infix arguments with a popup as feedback." :link (info-link "(magit-popup)") :group bindings
magit-popup-faces "Faces used by Magit-Popup." custom-declare-variable magit-popup-display-buffer-action funcall function #f(compiled-function () #<bytecode 0x1fa3d1d>) "The action used to
display a popup buffer.\n\nPopup buffers are displayed using `display-buffer' with the value\nof this option as ACTION argument.  You can also set this to nil\nand instead add an entry to
`display-buffer-alist'." :package-version (magit-popup . "2.4.0") :type sexp magit-popup-manpage-package #f(compiled-function () #<bytecode 0x1fa3d35>) "The package used to display
manpages.\nOne of `man' or `woman'." (choice (const man) (const woman)) magit-popup-show-help-echo #f(compiled-function () #<bytecode 0x1fa3d45>) "Show usage information in the echo area."
boolean magit-popup-show-common-commands #f(compiled-function () #<bytecode 0x1fa3d55>) "Whether to initially show section with commands common to all popups.\nThis section can also be
toggled temporarily using \\<magit-popup-mode-map>\\[magit-popup-toggle-show-common-commands]." (magit-popup . "2.9.0") magit-popup-use-prefix-argument #f(compiled-function () #<bytecode
0x1fa3d65>) "Control how prefix arguments affect infix argument popups.\n\nThis option controls the effect that the use of a prefix argument\nbefore entering a popup has.\n\n`default'  With
a prefix argument directly invoke the popup's\n           default action (an Emacs command), instead of bringing\n           up the popup.\n\n`popup'    With a prefix argument bring up the
popup, otherwise\n           directly invoke the popup's default action.\n\n`nil'      Ignore prefix arguments." (choice (const :tag "Call default action instead of showing popup" default)
(const :tag "Show popup instead of calling default action" popup) (const :tag "Ignore prefix argument" nil)) ...] 10)
  require(magit-popup nil t)
  (if (require (quote magit-popup) nil t) nil (defalias (quote magit-define-popup-switch) (function (lambda (&rest _) (magit--magit-popup-warning)))) (defalias (quote
magit-define-popup-option) (function (lambda (&rest _) (magit--magit-popup-warning)))) (defalias (quote magit-define-popup-variable) (function (lambda (&rest _)
(magit--magit-popup-warning)))) (defalias (quote magit-define-popup-action) (function (lambda (&rest _) (magit--magit-popup-warning)))) (defalias (quote magit-define-popup-sequence-action)
(function (lambda (&rest _) (magit--magit-popup-warning)))) (defalias (quote magit-define-popup-key) (function (lambda (&rest _) (magit--magit-popup-warning)))) (defalias (quote
magit-define-popup-keys-deferred) (function (lambda (&rest _) (magit--magit-popup-warning)))) (defalias (quote magit-change-popup-key) (function (lambda (&rest _)
(magit--magit-popup-warning)))) (defalias (quote magit-remove-popup-key) (function (lambda (&rest _) (magit--magit-popup-warning)))))
  eval-buffer(#<buffer  *load*-839362> nil "/home/alper/.emacs.d/elpa/magit-20200825.1251/magit-obsolete.el" nil t)  ; Reading at buffer position 3995
  load-with-code-conversion("/home/alper/.emacs.d/elpa/magit-20200825.1251/magit-obsolete.el" "/home/alper/.emacs.d/elpa/magit-20200825.1251/magit-obsolete.el" nil t)
  require(magit-obsolete)

byte-code("\301\302!\210\303\304!\210\303\305!\210\303\306!\210\303\307!\210\303\310!\210\303\311!\210\303\312!\210\303\313!\210\303\314!\210\303\315!\210\303\316!\210\303\317!\210\303\320!\2\
10\303\321!\210\303\322!\210\303\323!\210\303\324!\210\303\325!\210\303\326!\210\303\327!\210\303\330!\210\331\332\333\211#\204\200\0\303\334!\210\303\335!\210\303\336!\210\303\337!\210\303\3\
40!\210\303\341!\210\303\342!\210\303\343!\210\344\345\346\"\210\010\203\222\0\347 \210\350 \210\202\236\0\351\352\347\333#\210\351\352\350\333#\210\301\207" [after-init-time provide magit
require magit-status magit-refs magit-files magit-reset magit-branch magit-merge magit-tag magit-worktree magit-notes magit-sequence magit-commit magit-remote magit-clone magit-fetch
magit-pull magit-push magit-bisect magit-stash magit-blame magit-obsolete magit-submodule load "magit-autoloads" t magit-patch magit-subtree magit-ediff magit-gitignore magit-extras
git-rebase magit-imenu magit-bookmark eval-after-load bookmark #f(compiled-function () #<bytecode 0x1ea96c9>) magit-startup-asserts magit-version add-hook after-init-hook] 4)
  require(magit)
  eval-buffer(#<buffer  *load*-125346> nil "/home/alper/.emacs.d/elpa/magit-delta-20200518.2205/magit-delta.el" nil t)  ; Reading at buffer position 744
  load-with-code-conversion("/home/alper/.emacs.d/elpa/magit-delta-20200518.2205/magit-delta.el" "/home/alper/.emacs.d/elpa/magit-delta-20200518.2205/magit-delta.el" nil t)
  (magit-delta-mode 1)
  eval-buffer(#<buffer  *load*> nil "/home/alper/.emacs" nil t)  ; Reading at buffer position 77694
  load-with-code-conversion("/home/alper/.emacs" "/home/alper/.emacs" t t)
#f(compiled-function () #<bytecode 0x1e0f5d>)()
  command-line()
  normal-top-level()
```

**Comment by dandavison** [comment] 2020-08-27 18:30
Hi @avatar-lavventura, if you do not load `magit-delta` but instead `(require 'magit)` in your config file, do you see the same error?

**Comment by avatar-lavventura** [comment] 2020-08-27 22:12
@dandavison No I do not see any error. So using `(require 'magit)` instead of `(require 'magit-delta)` solves the issue

**Comment by avatar-lavventura** [comment] 2020-08-27 22:15
@dandavison yes I still see the same error

**Comment by dandavison** [comment] 2020-08-27 22:21
OK, so that suggests it's a problem with your magit setup then I think. Do you agree?

**Comment by avatar-lavventura** [comment] 2020-08-27 22:27
Yes I agree, so should I carry this issue to magit repo?

**Comment by dandavison** [comment] 2020-08-28 00:05
I suspect that it's not a bug in magit (or magit-delta) but rather something wrong with your local setup -- maybe the mixture of package versions you have locally aren't the expected ones. I think you're doing the right thing by asking on emacs.stackexchange for help; I've replied [there](https://emacs.stackexchange.com/questions/60326/debugger-entered-lisp-error-wrong-type-argument-sequencep-all-cl-intersectio/60352#60352). But let's close this, since currently we think that magit-delta isn't relevant.

**Comment by avatar-lavventura** [comment] 2020-08-28 08:19
@dandavison Thanks

**Closed as completed** 2020-08-28 08:19 UTC
